import urllib2
from saveTopic import saveBaiduTopics,saveTencentTopics,saveSohuTopics,saveNeteasyTopics
content1 = urllib2.urlopen('http://news.baidu.com').read()
content2 = urllib2.urlopen('http://news.qq.com').read()
content3 = urllib2.urlopen('http://news.sohu.com').read()
content4 = urllib2.urlopen('http://news.163.com').read()
#content5 = urllib2.urlopen('http://nytsyn.com').read()
content5 = urllib2.urlopen('http://baidu.com').read()
output1 = open('.\\source\\baidu.txt','w')
output1.write(content1)
output1.close()
output2 = open('.\\source\\tencent.txt','w')
output2.write(content2)
output2.close()
output3 = open('.\\source\\sohu.txt','w')
output3.write(content3)
output3.close()
output4 = open('.\\source\\neteasy.txt','w')
output4.write(content4)
output4.close()
output5 = open('.\\source\\newyorktimes.txt','w')
output5.write(content5)
output5.close()
saveBaiduTopics()
saveTencentTopics()
saveSohuTopics()
saveNeteasyTopics()
